apps/website/urls.py
from django.urls import path

from apps.website.views import (
    AboutUsView,
    CategoryDetailView,
    ContactView,
    CookiesView,
    IndexView,
    JobsView,
    MakeAppointmentView,
    PremiumLoansPageView,
    PrivacyPolicyView,
    ProjectListView,
    SingleProjectDetailView,
    TermsAndConditionsView,
)

app_name = 'website'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('make-appointment/', MakeAppointmentView.as_view(), name='make_appointment'),
    path('contacts/', ContactView.as_view(), name='contact_page'),
    path('jobs/', JobsView.as_view(), name='jobs_page'),
    path('premies-leningen/', PremiumLoansPageView.as_view(), name='premium_loans'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('cookie-policy/', CookiesView.as_view(), name='cookies_policy'),
    path('terms-and-conditions/', TermsAndConditionsView.as_view(), name='terms_policy'),
    path('projects/', ProjectListView.as_view(), name='project_list'),
    path('projects/<pk>/', SingleProjectDetailView.as_view(), name='project_single_detail'),
    path('<slug:slug>/', CategoryDetailView.as_view(), name='category_page_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.website.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
handler404 = 'apps.website.views.handler404'
handler500 = 'apps.website.views.handler500'

apps/website/models/about_us.py
from ckeditor.fields import RichTextField
from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill, Transpose

from apps.base.mixins import SingletonPageMixin
from apps.base.models import (
    AbstractSliderModel,
    MetaPageAbstractModel,
    TimeStampedModel,
)


class AboutUsPageModel(SingletonPageMixin, MetaPageAbstractModel):
    introduction_title = models.TextField()
    introduction_content = RichTextField()
    introduction_small_image = models.ImageField(
        upload_to='about_us/introduction_small_images/',
        verbose_name='introduction_small_image'
    )
    introduction_small_image_cut = ImageSpecField(
        source='introduction_small_image',
        processors=[
            Transpose(),
            ResizeToFill(
                width=265,
                height=269,
            )
        ],
        format='JPEG',
    )
    introduction_big_image = models.ImageField(
        upload_to='about_us/introduction_big_images/',
        verbose_name='introduction_big_image'
    )
    introduction_big_image_cut = ImageSpecField(
        source='introduction_big_image',
        processors=[
            Transpose(),
            ResizeToFill(
                width=386,
                height=394,
            )
        ],
        format='JPEG',
    )
    team_title = models.CharField(max_length=255)

    def __str__(self):
        return 'About Us Page'


class AboutUsImageSliderModel(AbstractSliderModel):
    about_us = models.ForeignKey(AboutUsPageModel, on_delete=models.CASCADE, related_name='sliders')


class AboutUsTeamMemberModel(TimeStampedModel):
    name = models.CharField(max_length=255)
    role = models.CharField(max_length=255)
    image = models.ImageField(
        upload_to='about_us/team_members/',
        verbose_name='about_us_team_member'
    )
    image_cut = ImageSpecField(
        source='image',
        processors=[
            Transpose(),
            ResizeToFill(
                width=386,
                height=394,
            )
        ],
        format='JPEG',
    )
    about_us = models.ForeignKey(AboutUsPageModel, on_delete=models.CASCADE, related_name='team_members')


class AboutUsHistoryModel(TimeStampedModel):
    year = models.CharField(max_length=10)
    title = models.TextField()
    image = models.ImageField(
        upload_to='about_us/histories/',
        verbose_name='about_us_history'
    )
    image_cut = ImageSpecField(
        source='image',
        processors=[
            Transpose(),
            ResizeToFill(
                width=386,
                height=394,
            )
        ],
        format='JPEG',
    )
    about_us = models.ForeignKey(AboutUsPageModel, on_delete=models.CASCADE, related_name='histories')

apps/website/models/category_page.py
from ckeditor.fields import RichTextField
from django.db import models
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill, Transpose

from apps.base.models import (
    AbstractCalculatorBlock,
    AbstractResultBlock,
    AbstractSliderModel,
    IntroductionAbstractModel,
    MetaPageAbstractModel,
    SlugNameMixin,
    TimeStampedModel,
)


class CategoryPage(SlugNameMixin, IntroductionAbstractModel, MetaPageAbstractModel):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, max_length=100, blank=True, null=True)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='children', on_delete=models.CASCADE)
    related_projects_block_title = models.TextField(null=True, blank=True)
    related_projects_block_sub_title = models.TextField(null=True, blank=True)
    completed_projects_block_title = models.TextField(null=True, blank=True)
    completed_projects_block_sub_title = models.TextField(null=True, blank=True)
    completed_projects_block_description = models.TextField(null=True, blank=True)
    show_booking_section = models.BooleanField(default=False)
    index_preview_icon = models.FileField(
        upload_to='index_preview_icons/',
        verbose_name='index_preview_icon',
        blank=True,
        null=True
    )
    index_preview_text = models.TextField(
        blank=True,
        null=True
    )

    class Meta:
        ordering = ['order_by']

    def __str__(self):
        return self.name


class CategorySliderModel(AbstractSliderModel):
    page = models.ForeignKey(CategoryPage, on_delete=models.CASCADE, related_name='sliders')


class RelatedProjects(TimeStampedModel):
    page = models.ForeignKey(CategoryPage, on_delete=models.CASCADE, related_name='related_projects')
    title = models.TextField()
    description = models.TextField()
    image = models.ImageField(
        upload_to='related_projects/',
        verbose_name='image'
    )
    image_cut = ImageSpecField(
        source='image',
        processors=[
            Transpose(),
            ResizeToFill(
                width=330,
                height=363,
            )
        ],
        format='JPEG',
    )
    path_to_page = models.CharField(null=True, blank=True, max_length=100)
    button_text = models.CharField(default='Meer informatie', max_length=60)


class CalculatorBlock(AbstractCalculatorBlock):
    page = models.OneToOneField(CategoryPage, on_delete=models.CASCADE, related_name='calculator_block')


class ContentBlock(TimeStampedModel):
    page = models.OneToOneField(CategoryPage, related_name="content_block", on_delete=models.CASCADE)
    title = models.TextField()
    sub_title = models.TextField()
    content = RichTextField(verbose_name='Content Block Content')
    image = models.ImageField(
        upload_to='content_block/before/',
        verbose_name='image'
    )
    image_cut = ImageSpecField(
        source='image',
        processors=[
            Transpose(),
            ResizeToFill(
                width=463,
                height=500,
            )
        ],
        format='JPEG',
    )


class VideoBlock(TimeStampedModel):
    page = models.OneToOneField(CategoryPage, related_name="video_block", on_delete=models.CASCADE)
    title = models.TextField()
    sub_title = models.TextField()
    video = models.FileField(
        upload_to='video_block/',
        verbose_name='Video'
    )
    video_poster = models.ImageField(
        upload_to='video_poster/',
        verbose_name='video_poster'
    )


class ProjectBlock(TimeStampedModel):
    page = models.OneToOneField(CategoryPage, related_name="project_block", on_delete=models.CASCADE)
    title = models.TextField()
    sub_title = models.TextField()
    content = models.TextField()


class ResultBlock(AbstractResultBlock):
    page = models.OneToOneField(CategoryPage, related_name="result_block", on_delete=models.CASCADE)


class AnimationBlock(TimeStampedModel):
    class AnimationType(models.TextChoices):
        CREPI = 'crepi', 'crepi'
        DAKWERGEN = 'dakwerken', 'dakwerken'
        RAMEN = 'ramen_deuren', 'ramen_deuren'
        GEBELISOLATIE = 'gevelisolatie', 'gevelisolatie'

    animation_type = models.CharField(
        max_length=30,
        choices=AnimationType.choices,
        default=AnimationType.CREPI
    )
    animation_turn = models.BooleanField(default=True)
    page = models.OneToOneField(CategoryPage, related_name="animation_block", on_delete=models.CASCADE)


class CTAOptionalBlock(TimeStampedModel):
    page = models.OneToOneField(CategoryPage, related_name="cta", on_delete=models.CASCADE)
    title = models.TextField()
    sub_title = models.TextField()

apps/website/models/jobs_page.py
from ckeditor.fields import RichTextField
from django.db import models

from apps.base.models import (
    AbstractSliderModel,
    IntroductionAbstractModel,
    MetaPageAbstractModel,
    SlugNameMixin,
    TimeStampedModel,
)


class JobsPageModel(IntroductionAbstractModel, MetaPageAbstractModel):
    jobs_header = models.TextField()
    introduction_left_content = RichTextField(verbose_name='Introduction Left Content', null=True, blank=True)

    def __str__(self):
        return 'Jobs Page'


class JobsImageSliderModel(AbstractSliderModel):
    page = models.ForeignKey(JobsPageModel, on_delete=models.CASCADE, related_name='sliders')


class VacationModel(SlugNameMixin, TimeStampedModel):
    page = models.ForeignKey(JobsPageModel, on_delete=models.CASCADE, related_name='vacations')
    title = models.TextField()
    description = models.TextField()
    content = RichTextField()
    order_by = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('order_by', )

apps/website/models/make_appointment.py
from django.db import models

from apps.base.mixins import SingletonPageMixin
from apps.base.models import (
    AbstractSliderModel,
    MetaPageAbstractModel,
    TimeStampedModel,
)


class MakeAppointmentPageModel(SingletonPageMixin, MetaPageAbstractModel):
    introduction_title = models.TextField()
    introduction_sub_title = models.TextField()

    def __str__(self):
        return 'Make Appointment Page'


class MakeAppointmentSlider(AbstractSliderModel):
    parent = models.ForeignKey(MakeAppointmentPageModel, on_delete=models.CASCADE, related_name='sliders')


class MakeAppointmentAdvantage(TimeStampedModel):
    title = models.TextField()
    text = models.TextField()
    parent = models.ForeignKey(MakeAppointmentPageModel, on_delete=models.CASCADE, related_name='advantages')


class ServicesAppointment(TimeStampedModel):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Feedback(TimeStampedModel):
    full_name = models.CharField(max_length=200)
    email = models.EmailField()
    phone = models.CharField(max_length=30)
    message = models.TextField()
    post_code = models.CharField(max_length=30)
    estimate_facade_area = models.CharField(max_length=100)
    image = models.ImageField(
        upload_to='feedbacks/',
        verbose_name='feedback',
        null=True,
        blank=True
    )
    appointments = models.ManyToManyField("ServicesAppointment", related_name='feedbacks', null=True, blank=True)

    def __str__(self):
        return f'{self.email} {self.created_at}'

apps/website/models/privacy_policy.py
from ckeditor.fields import RichTextField
from django.db import models

from apps.base.mixins import SingletonPageMixin
from apps.base.models import MetaPageAbstractModel, TimeStampedModel


class BasePolicyAbstractModel(MetaPageAbstractModel, TimeStampedModel):
    head_title = models.TextField(default="Privacy policy")
    title = models.TextField()
    content = RichTextField()

    class Meta:
        abstract = True


class BasePolicySubBlockAbstractModel(TimeStampedModel):
    title = models.TextField()
    content = RichTextField()

    class Meta:
        abstract = True


class PrivacyPolicyModel(BasePolicyAbstractModel):

    def __str__(self):
        return "Privacy Policy"


class PrivacyPolicySubBlockModel(BasePolicySubBlockAbstractModel):
    page = models.ForeignKey(PrivacyPolicyModel, on_delete=models.CASCADE, related_name="sub_blocks")

    def __str__(self):
        return f"Privacy Policy sub block {self.pk}"


class CookieModel(BasePolicyAbstractModel):
    def __str__(self):
        return "Cookie Policy"


class CookieSubBlockModel(BasePolicySubBlockAbstractModel):
    page = models.ForeignKey(CookieModel, on_delete=models.CASCADE, related_name="sub_blocks")

    def __str__(self):
        return f"Cookie sub block {self.pk}"


class TermsAndConditionsModel(BasePolicyAbstractModel):

    def __str__(self):
        return "Terms And Conditions"


class TermsAndConditionsSubBlockModel(BasePolicySubBlockAbstractModel):
    page = models.ForeignKey(TermsAndConditionsModel, on_delete=models.CASCADE, related_name="sub_blocks")

    def __str__(self):
        return f"Terms And Conditions {self.pk}"

templates/pages/about_us.html
{% extends 'base.html' %}
{% block content %}

    {% include 'includes/slider_head.html' %}

    <section class="introduction introduction-with-imgs --gray-bg">
        <div class="container">
            <div class="introduction__inner">
                <div class="introduction__left">
                    <div class="introduction__header" data-aos="fade-up">
                        <h5 class="subtitle">CLEYS</h5>
                        <h2 class="like-h3">{{ page_model.introduction_title }}</h2>
                    </div>
                    <div class="introduction__desc --content" data-aos="fade-up">
                    {{ page_model.introduction_content | safe }}
                    </div>
                    <div class="btn-block">
                        <a href="#" class="btn --btn-arrow">Ons verhaal</a>
                    </div>
                </div>
                <div class="introduction__right">
                    <div class="introduction__imgs">
                        <div class="img big">
                            <img src="{{ page_model.introduction_big_image_cut.url }}" alt="">
                        </div>
                        <div class="img small">
                            <img src="{{ page_model.introduction_small_image_cut.url }}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="team">
        <div class="container">
            <div class="team__inner">
                <div class="team__header section-title --section-title-center">
                    <h5 class="subtitle">team</h5>
                    <h2 class="like-h3">{{ page_model.team_title }}</h2>
                </div>
                <div class="team__list">
                    {% for member in page_model.team_members.all %}
                        <div class="team__member" data-aos="fade-up">
                            <div class="team__member-img">
                                <img src="{{member.image_cut.url }}" alt="">
                            </div>
                            <div class="team__member-content">{{ member.name }} <span>{{ member.role }}</span></div>
                        </div>
                    {% endfor %}
                    
                    <div data-aos="fade-up">
                        <a href="{% url 'website:jobs_page' %}" class="team__link">
                            <h3 class="like-h3">Kom je ook werken bij Cleys?</h3>
                            <div>Wij zijn altijd op zoek naar talent!</div>
                            <span class="read-more --white">bekijk vacatures</span>
                        </a>
                    </div>
                    </div>
                </div>
            </div>
    </section>

    <section class="history --blue-bg">
        <span class="logo-bg" data-aos="fade-up"></span>
        <div class="container">
            <div class="history__inner">
                <div class="history__header section-title --section-title-center">
                    <h5 class="subtitle">GESCHIEDENIS</h5>
                    <h2>Cleys door de jaren heen</h2>
                </div>
                <div class="history__list">
                    {% for  history_item in page_model.histories.all %}
                    <div class="history__item" data-aos="fade-up">
                        <div class="history__item-date-img">
                            <div class="history__item-date">{{ history_item.year }}</div>
                            <h3 class="history__item-title">{{ history_item.title }}</h3>
                            <div class="history__item-img">
                                <img src="{{ history_item.image_cut.url }}" alt="">
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

    {% include 'includes/reviews.html' %}
    
{% endblock %}

templates/pages/all_projects.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    
    {% include 'includes/slider_head.html' %}
    <section class="projects-overview">
        <div class="container">
            <div class="projects-overview__header section-title --section-title-center">
                <h5 class="subtitle">{{ page_model.sub_title }}</h5>
                <h2 class="like-h3">{{ page_model.title }}</h2>
            </div>
            <nav class="projects-overview__filter">
                <ul>
                    <li class="active"><a href="{% url 'website:project_list' %}">Alles ({{ projects_count }})</a></li>
                    {% for category in categories %}
                        <li><a href="?category={{ category.slug }}">{{ category.name }}</a></li>
                    {% endfor %}
                </ul>
            </nav>
            <div class="projects-overview__list">
                <!-- NOTE every odd "project-single" element has class="--long"
                    "--link" class can be apllied only to block which have '--long' class (also have comlitely different structure) 
                -->
                {% for project in projects %}
                    {% if forloop.counter == 5 %}
                        <a href="#" class="project-single --long --link" data-aos="fade-up">
                            <div class="project-single__link">
                                <h3 class="like-h2">Wil je dat jouw project hier ook tussen staat?</h3>
                                <div>We trachten van ieder project een topreferentie te maken, om zo nieuwe klanten te overtuigen.</div>
                                <span class="read-more --white">offerte vragen</span>
                            </div>
                        </a>
                    {% endif %}

                    {% if not forloop.counter|divisibleby:2 %}
                        <a href="{% url 'website:project_single_detail' pk=project.pk %}" class="project-single --long" data-aos="fade-up">
                    {% else %}
                         <a href="{% url 'website:project_single_detail' pk=project.pk %}" class="project-single" data-aos="fade-up">
                    {% endif %}
                            <div class="project-single__img">
                                {% for item in project.preview_images.all %}
                                    <img src="{{ item.image.url }}" alt="">
                                {% endfor %}
                            </div>
                            <ul class="tag-list">
                                {% for category in project.related_categories.all %}
                                    <li>{{ category.name }}</li>
                                {% endfor %}
                            </ul>
                        </a>
                {% endfor %}
            
            </div>
            <nav role="navigation" aria-label="Pagination Navigation">
            {% if pagination %}
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="prev"><a href="?page={{ page_obj.previous_page_number }}{{ get_params }}" aria-label="Previous Page">&lt;</a>
                    {% endif %}
                        
                    {% if page_obj.number|add:'-4' > 1 %}
                        <li><a href="?page=1{{ get_params }}">1</a></li>
                        {% if page_obj.number|add:'-5' > 1 %}
                            <li><span>...</span></li>
                        {% endif %}
                    {% endif %}
                    
                    {% for i in page_obj.paginator.page_range %}
                        {% if page_obj.number == i %}
                            <li class="active"><a href="#" aria-current="true">{{ i }}</a></li>
                        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                            <li><a href="?page={{ i }}{{ get_params }}">{{ i }}</a></li>
                            
                        {% endif %}
                    {% endfor %}
                        
                    {% if page_obj.paginator.num_pages > page_obj.number|add:'4' %}
                        {% if page_obj.paginator.num_pages >  page_obj.number|add:'5'%}
                            <li><span>...</span></li>
                        {% endif %}
                        <li><a href="?page={{ page_obj.paginator.num_pages }}{{ get_params }}">{{ page_obj.paginator.num_pages }}</a></li>
                    {% endif %}
                    
                    {% if page_obj.has_next %}
                         <li class="next"><a href="?page={{ page_obj.next_page_number }}{{ get_params }}" aria-label="Next Page">&gt;</a></li>
                    {% else %}
                        <li class="disabled"><span><i class="fa fa-chevron-right" aria-hidden="true"></i></span></li>
                    {% endif %}
                    
                </ul>
            {% endif %}
            </nav>
        </div>
    </section>
    {% include 'includes/sections/calculator_section.html' %}
    {% include 'includes/reviews.html' %}

{% endblock %}

templates/pages/contact.html
{% extends 'base.html' %}
{% block content %}
{% load recaptcha3 %}
{% load static %}

        {% include 'includes/slider_head.html' %}
        
        <section class="contact">
            <div class="container">
                <div class="contact__inner">
                    <div class="contact__content">
                        <div class="contact-info">
                            <a href="mailto:{{ contact_info.email }}">
                                <div class="icon">
                                    <img src="{% static 'assets/images/icon-mail-white.svg' %}" alt="">
                                </div>
                                <div><span>Mail ons</span>{{ contact_info.email }}</div>
                            </a>
                            <a href="tel:{{ contact_info.phone }}">
                                <div class="icon">
                                    <img src="{% static 'assets/images/icon-tel-white.svg' %}" alt="">
                                </div>
                                <div><span>Bel ons op</span>{{ contact_info.phone }}</div>
                            </a>
                        </div>
                        <div class="contact__title">
                            <h2 class="like-h4">{{ page_model.address_title }}</h2>
                        </div>
                        <address>
                            {% for paragraph_model in page_model.address_paragraphs.all %}
                                {{ paragraph_model.paragraph }} <br>
                            {% endfor %}
                        </address>
                        <a href="{{ page_model.address_link }}">{{ page_model.link_title }}</a>
                        <div class="contact__title">
                            <h2 class="like-h4">Social media</h2>
                        </div>
                        <div class="soc-block">
                            <a href="{{ contact_info.facebook_link }}" target="_blank" rel="noopener noreferrer" class="facebook" aria-label="facebook"></a>
                            <a href="{{ contact_info.instagram_link }}" target="_blank" rel="noopener noreferrer" class="instagram" aria-label="instagram"></a>
                        </div>
                    </div>
                    <div class="contact__form">
                        <form action="" method="post">
                            {% csrf_token %}
                            {{ form.recaptcha }}
                            {{ form.recaptcha.errors }}
                            <div class="form-row">
                                <div class="col col-1">
                                    <label for="{{ form.full_name.id_for_label }}">Volledige naam *</label>
                                    {{ form.full_name }}
                                </div>
                                <div class="col col-1">
                                    <label for="{{ form.email.id_for_label }}">E-mailadres *</label>
                                    {{ form.email }}
                                </div>
                                <div class="col col-1">
                                    <label for="{{ form.phone.id_for_label }}">GSM / Tel. Nr.  *</label>
                                    {{ form.phone }}
                                </div>
                                <div class="col col-1">
                                    <label for="{{ form.phone.id_for_label }}">Postcode*</label>
                                    {{ form.post_code }}
                                </div>
                                <div class="col col-1">
                                    <label for="{{ form.phone.id_for_label }}">Bericht*</label>
                                    {{ form.message }}
                                </div>

                                <div class="col col-1 submit-row">
                                    <div class="privacy">Als je dit verstuurt ga je akkoord met onze <a href="{% url 'website:privacy_policy' %}" target="_blank">privacy policy</a>.</div>
                                    <button type="submit" class="btn --btn-arrow">Afspraak boeken</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>

        {% include 'includes/reviews.html' %}

{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

    <!-- NOTE "showcase" almost on all pages, class="--big" only on the home page -->
     {% include 'includes/slider_head_index_only.html' %}
    
    {% include 'includes/sections/introduction_section.html' %}
    
    <section class="services-overview">
        <div class="container">
            <div class="services-overview__inner --blue-bg">
                <span class="logo-bg" aria-hidden="true" data-aos="fade-up"></span>
                <div class="services-overview__header" data-aos="fade-up">
                    <h5 class="subtitle">{{ page_model.overview_sub_title }}</h5>
                    <h2>{{ page_model.overview_title }}</h2>
                </div>
                <div class="services-overview__list" data-aos="fade-up">
                    {% for category in categories %}
                          <a href="{% url 'website:category_page_detail' slug=category.slug %}" class="services-overview__item">
                        <div class="services-overview__item-header">
                            <div class="icon">
                                {% if category.index_preview_icon %}
                                <img src="{{ category.index_preview_icon.url }}" alt="">
                                {% endif %}
                            </div>
                            <h3 class="like-h5">{{ category.name }}</h3>
                        </div>
                        <div class="services-overview__item-content">{{ category.index_preview_text }}</div>
                        <span class="read-more --white">Lees meer</span>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    
    {% include 'includes/sections/booking_section.html' %}
    
   {% include 'includes/sections/calculator_section.html' %}

    {% include 'includes/sections/projects_section.html' %}

    {% include 'includes/reviews.html' %}
{% endblock %}

templates/pages/jobs_page.html
{% extends 'base.html' %}
{% block content %}

        {% include 'includes/slider_head.html' %}
        {% include 'includes/sections/introduction_section.html' %}
        <section class="jobs">
                <div class="container">
                    <div class="jobs__header">
                        <h2 class="like-h3">Onze vacatures</h2>
                    </div>
                    <div class="jobs__inner">
                        <div class="jobs__nav">
                            <ul>
                                {% for vacancy in  page_model.vacations.all %}
                                    {% if vacancy.slug == active_vacancy.slug %}
                                        <li><a class="active" href="{% url 'website:jobs_page' %}?vacancy_slug={{ vacancy.slug }}">{{ vacancy.name }}</a></li>
                                    {% else %}
                                        <li><a href="{% url 'website:jobs_page' %}?vacancy_slug={{ vacancy.slug }}">{{ vacancy.name }}</a></li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="jobs__content">
                            <div class="article-body --content">
                                <h3>{{ active_vacancy.title }}</h3>
                                <p>{{ active_vacancy.description }}</p>
                                   {{ active_vacancy.content | safe }}
                            </div>
                            <div class="jobs__content-footer">
                                <h6>Geïnteresseerd?</h6>
                                <p>Stuur jouw cv en motivvatiebreif door naar <a href="mailto:jobs@cleys.be">jobs@cleys.be</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
    
        {% include 'includes/reviews.html' %}

{% endblock %}