apps/website/urls.py
from django.urls import path

from apps.website.views import (
    AboutUsView,
    CategoryDetailView,
    ContactView,
    CookiesView,
    IndexView,
    JobsView,
    MakeAppointmentView,
    PremiumLoansPageView,
    PrivacyPolicyView,
    ProjectListView,
    SingleProjectDetailView,
    TermsAndConditionsView,
)

app_name = 'website'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about-us/', AboutUsView.as_view(), name='about_us'),
    path('make-appointment/', MakeAppointmentView.as_view(), name='make_appointment'),
    path('contacts/', ContactView.as_view(), name='contact_page'),
    path('jobs/', JobsView.as_view(), name='jobs_page'),
    path('premies-leningen/', PremiumLoansPageView.as_view(), name='premium_loans'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('cookie-policy/', CookiesView.as_view(), name='cookies_policy'),
    path('terms-and-conditions/', TermsAndConditionsView.as_view(), name='terms_policy'),
    path('projects/', ProjectListView.as_view(), name='project_list'),
    path('projects/<pk>/', SingleProjectDetailView.as_view(), name='project_single_detail'),
    path('<slug:slug>/', CategoryDetailView.as_view(), name='category_page_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.website.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
handler404 = 'apps.website.views.handler404'
handler500 = 'apps.website.views.handler500'

templates/includes/footer.html
{% load static %}
<div class="footer-top">
    <div class="container --small">
        <div class="footer-top__inner">
            <div class="footer-top__col --intro">
                <div class="footer-top__logo">
                    <img src="{% static 'assets/images/Cleys.svg' %}" alt="">
                </div>
                <div class="footer-top__desc">{{ footer_info.description }}</div>
            </div>
            <div class="footer-top__col --contact">
                <div class="f-contact">
                    <a href="mailto:info@cleys.be">
                        <div class="icon">
                            <img src="{% static 'assets/images/icon-mail.svg' %}" alt="">
                        </div>
                        <div>Mail ons <span>{{ contact_info.email }}</span></div>
                    </a>
                    <a href="tel:003238779323">
                        <div class="icon">
                            <img src="{% static 'assets/images/icon-tel.svg' %}" alt="">
                        </div>
                        <div>Bel ons op <span>{{ contact_info.phone }}</span></div>
                    </a>
                    <a href="https://www.gevelcalculator.cleys.be/">
                        <div class="icon">
                            <img src="{% static 'assets/images/icon-calc.svg' %}" alt="">
                        </div>
                        <div>Bereken jouw prijs <span>Gebruik onze calculator</span></div>
                    </a>
                </div>
            </div>
            <div class="footer-top__col --menu">
                <h6 class="subtitle">Diensten</h6>
                <ul>
                     {% for page in category_pages %}
                          <li><a href="{% url 'website:category_page_detail' slug=page.slug %}"> {{ page.name }} </a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="footer-top__col --menu">
                <h6 class="subtitle">Menu</h6>
                <ul>
                    <li><a href="{% url 'website:about_us' %}">Over ons</a></li>
                   <li><a href="{% url 'website:project_list' %}">Projecten</a></li>
                    <li><a href="{% url 'website:premium_loans' %}">Premies & leningen</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="footer-bottom">
    <div class="container">
        <div class="footer-bottom__inner">
            <ul>
                <li><a href="{% url 'website:terms_policy' %}">Algemene voorwaarden</a></li>
                <li><a href="{% url 'website:privacy_policy' %}">Privacy Policy</a></li>
                <li><a href="{% url 'website:cookies_policy' %}">Cookiestatement</a></li>
            </ul>
            <div class="codelines">#codedwithlove by <a href="https://codelines.be" target="_blank" rel="noopener noreferrer">Codelines</a></div>
        </div>
    </div>
</div>

templates/includes/header-menu.html
{% load static %}
<div class="container">
    <div class="logo hide-desktop"><a href="/" aria-label="Cleys"><img src="{% static 'assets/images/Cleys.svg' %}" alt=""></a></div>
    <div id="hamburger">
        <span></span>
        <span></span>
        <span></span>
    </div>
</div>

<nav class="header-nav">
    <div class="header-nav__top">
        <div class="container">
            <div class="header-nav__top-inner">
                <div class="header-nav__reviews">
                    <div>{{ reviews.stars }}/5</div>
                    <div class="stars">
                        <div class="solid"></div>
                        <div class="solid"></div>
                        <div class="solid"></div>
                        <div class="solid"></div>
                        <div class="solid"></div>
                    </div>
                    <span>({{ reviews.all_reviews }} reviews)</span>
                </div>
                <div class="header-nav__contact">
                    <a href="mailto:{{ contact_info.email }}"><img src="{% static 'assets/images/icon-mail.svg' %}" alt="">{{ contact_info.email }}</a>
                    <a href="tel:{{ contact_info.phone }}"><img src="{% static 'assets/images/icon-tel.svg' %}" alt="">{{ contact_info.phone }}</a>
                </div>
            </div>
        </div>
    </div>
    <div class="header-nav__bottom">
        <div class="container">
            <div class="header-nav__bottom-inner">
                <div class="logo hide-mobile"><a href="/" aria-label="Cleys"><img src="{% static 'assets/images/Cleys.svg' %}" alt=""></a></div>
                <ul class="main-menu">
                    <li class="submenu {{ sub_menu_active }}">
                        <span>Wat we doen</span>
                        <div class="submenu-child">
                            <ul>
                                {% for page in category_pages %}
                                    {% if not page.parent %}
                                        <li>
                                        <a href="{% url 'website:category_page_detail' slug=page.slug %}"> {{ page.name }} </a>
                                        {% if page.children.all %}
                                            <ul>
                                            {% for page_child in page.children.all %}
                                                <li><a href="{% url 'website:category_page_detail' slug=page_child.slug %}"> {{ page_child.name }} </a></li>
                                            {% endfor %}
                                            </ul>
                                        {% endif %}
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                    <li class="{{ about_us_active }}"><a href="{% url 'website:about_us' %}">Over ons</a></li>
                    <li class="{{ project_list_active }}"><a href="{% url 'website:project_list' %}">Projecten</a></li>
                    <li class="{{ premium_loans_active }}"><a href="{% url 'website:premium_loans' %}">Premies & Leningen</a></li>
                    <li class="{{ contact_page_active }}"><a href="{% url 'website:contact_page' %}">Contact</a></li>
                </ul>
                <div class="btn-block">
                    <a href="https://www.gevelcalculator.cleys.be/" target="_blank" class="btn">Calculator</a>
                    <a href="{% url 'website:make_appointment' %}" class="btn --btn-transparent-orange">Boek afspraak</a>
                </div>
            </div>
        </div>
    </div>
</nav>

<div id="menu-overlay" class="overlay"></div>

templates/includes/slider_head.html
<section class="showcase --blue-bg">
        {% if page_model.show_slider %}
            <div class="showcase__slider js-showcase-slider --flex-slider">
        {% else %}
            <div class="showcase__inner">
        {% endif %}

            {% for slider in page_model.sliders.all %}
                <div class="showcase__item">
                    <div class="showcase__item-inner">
                        {% if slider.banner_image %}
                            <div class="showcase__bg">
                                <img src="{{ slider.banner_image.url }}" alt="">
                            </div>
                        {% endif %}
                        <div class="container">
                            <div class="showcase__content">
                                <h1>{{ slider.slider_title }}</h1>
                                <div class="showcase__desc">{{ slider.slider_body }}</div>
                                <div class="showcase__btn-block btn-block">
                                    {% if page_model.show_send_reviews_button %}
                                        <div>
                                            <a href="{% url 'website:make_appointment' %}" target="_blank" class="btn --btn-transparent-white --btn-arrow">Gratis offerte</a>
                                        </div>
                                    {% else %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
</section>

templates/includes/slider_head_index_only.html
<section class="showcase --big --blue-bg">     
        {% if page_model.show_slider %}
            <div class="showcase__slider js-showcase-slider --flex-slider">
        {% else %}
            <div class="showcase__inner">
        {% endif %}
         {% for slider in page_model.sliders.all %}
            <div class="showcase__item">
                <div class="showcase__item-inner">
                    <div class="showcase__bg">                                
                        <picture>
                            <!-- NOTE for showcase "--big" it is advisable to add to backend a field for vertical image for best view on mobile devices (~ proportion of image is 9:16). Use this image in <source> element below -->
                            <source srcset="{{ slider.banner_image.url }}" media="(orientation: portrait)" />
                            <img src="{{ slider.banner_image.url }}" alt="">
                        </picture>
                    </div>
                    <div class="container">
                        <div class="showcase__content">
                            <h1>{{ slider.slider_title }}</h1>
                            <div class="showcase__desc">{{ slider.slider_body }}</div>
                            <div class="showcase__btn-block btn-block">
                                <div>
                                    <a href="https://www.gevelcalculator.cleys.be/" target="_blank" class="btn --btn-arrow">Gebruik de gevelcalculator</a>
                                    <span>Bereken jouw prijs in 1 minuut</span>
                                </div>
                                <div>
                                    <a href="{% url 'website:about_us' %}" class="btn --btn-arrow --btn-white">Boek een afspraak</a>
                                    <span>Vrijblijvende analyse ter plaatse</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </section>